### ISSUE TITLE
Error: bin/compile: 10: export: CF_ZONE_ID,: bad variable name

### ISSUE THREAD

**Issue by stevelacey** [jamesmartin/cloudflare-cache-purge-buildpack#1]
Hey! great buildpack – I am getting this error though:

```
bin/compile: 10: export: CF_ZONE_ID,: bad variable name
```

I assume the problem is the comma... but I am not sure where it's coming from, `export_env_dir` looks good to me.

(Yes I have set the env vars)

**Comment by marvinrabe** [comment]
Hey,

I had the same issue. I removed everything related to export_env_dir and now it works perfectly.

Have a look at this: https://github.com/marvinrabe/cloudflare-cache-purge-buildpack

Regards,
Marvin

**Comment by jamesmartin** [comment]
@marvinrabe thanks for responding to this issue. Rather than maintaining a separate fork, would you like to open a Pull Request and merge your changes into this repository?

**Comment by marvinrabe** [comment]
@jamesmartin Sure.

But why is there this `export_env_dir` script? I just removed it to get the bug fixed. I dont think this would be suitable for a pull request now because this repository doesnt specify any versions. So my pull request would probably break the buildpack for people who rely on `export_env_dir`.

And the other thing is: I dont tested my changes on Heroku. I am using Dokku. Its similiar but I dont know how this buildpack behaves on Heroku.

**Comment by jamesmartin** [comment]
> And the other thing is: I dont tested my changes on Heroku. I am using Dokku. Its similiar but I dont know how this buildpack behaves on Heroku.

I didn't realize you were targeting Dokku. This buildpack has only been tested on Heroku, so I can imagine there would be some incompatibilities.

**Comment by itayganor** [comment]
> Hey,
> 
> I had the same issue. I removed everything related to export_env_dir and now it works perfectly.
> 
> Have a look at this: https://github.com/marvinrabe/cloudflare-cache-purge-buildpack
> 
> Regards,
> Marvin

Three years later and I get this error too. Your fork is no longer available :(

Working on dokku too.
